#!/bin/bash

for dir in $1/*/
do
  dirc=${dir%*/}
  dirname=${dirc##*/}
  if [ $dirname = "ilsvrc-test" ]; then
    continue;
  else
    mvname=${dirname:11}
    echo $mvname
    mv $1/$dirname/ $1/"ilsvrc-test"/$mvname
  fi 
done
